### ISSUE TITLE
argument error

### ISSUE THREAD

**Issue by muzi-8** [KangBK0120/CAM#2]
RuntimeError：avg_pool2d():argument 'input'(position 1)must be Variable,not tuple

**Comment by KangBK0120** [comment]
Hi, There are several fixes I forgot to commit.
However, I deleted all files after I made first commit.
I'm trying to debug it as soon as possible.
Could you tell me where you got that error?

**Comment by gchoi** [comment]
There is an error found:
in "model.py", NameError: name 'weights_init' is not defined.

**Comment by KangBK0120** [comment]
I'll debug the codes as soon as possible in this week.
After I made some changes, I'll notice on this issue. please re-fork after it.
Sorry for the inconvenience.

**Comment by KangBK0120** [comment]
I pushed new codes. However, I cannot access GPU environments right now. 
So if there are any errors, please let me know.

As I mentioned in README, I try to reflect pytorch 0.4.0 updates.
If you use older ones, please update pytorch.
