### ISSUE TITLE
Upgrade to PyTorch 1.0.0

### ISSUE THREAD

**Issue by deepandas11** [KangBK0120/CAM#4]
You could edit the code to use the cuda() function instead of the to() function, when loading the model and data to the device.

**Comment by KangBK0120** [comment]
Hi, thanks for the issue.

I will modify the codes to support pytorch 1.0 ASAP.

**Comment by KangBK0120** [comment]
As far as I know, using .to() is a more appropriate way to handle both CPU and GPU cases.
Anyway, I modified some codes. So please report if there are any errors. 
Thanks!
