### ISSUE TITLE
Create CAM from multiple channels 

### ISSUE THREAD

**Issue by kartik1395** [KangBK0120/CAM#5]
How can we create cam from a layer that has more than 1 channels ?

**Comment by KangBK0120** [comment]
As far as I know, the basic concept of CAM is having channels as many as the number of classes to classify in the last layer.

So could you explain more about "multiple channels"?

**Comment by kartik1395** [comment]
I wanted to make CAM not on the last conv layer of the network but on an intermediate layer. However I realized this is the drawback of CAM. Instead I can use Grad-CAM. Thanks for the easy implementation of CAM though!!

**Comment by KangBK0120** [comment]
Thanks for the comment and have a nice day!
